### ISSUE TITLE
More adequate documentation for lay people needed.

### ISSUE THREAD

**Issue by slipgatekid** [FoxUSA/OpenNote#195]
The note taking and organizational aspect of the program is fairly straight forward and exciting to use. However, as a non-programmer the documentation isn't complete enough for more extended use beyond the demo. Questions arise such as, how does one run the program offline? Launching the downloaded index.html brings up a page with a version stamp and that's it. Also, the github page suggests to use the demo at foxusa, this would be fine but the documentation doesn't describe how to configure the demo to save notes locally, and I'm not talking about exporting them to a zip file. What is the replication url setting? Is it possible for a user to configure the app to save directly to services like dropbox? I would love to use OpenNote more extensively but until these questions can be answered it will remain a curiousity. Thanks.

edit: After installing the latest OpenNote version on my website it looks like the editor CKEditor does not ship with OpenNote. Are there instructions for getting this to work?

**Comment by FoxUSA** [comment]
> However, as a non-programmer the documentation isn't complete enough for more extended use beyond the demo.
I feel you. I use this every day. Its put out there so other people can use if it fits their use case. Not enough community involvement to get a pulse on how technical the documentation needs to be. I don't know what you don't know. So I write for me.

> Questions arise such as, how does one run the program offline?
It just works. Once you load the site in your browser it gets saved. You simply go to the site when you are offline.

> What is the replication url setting? 
The url you connect to couchdb with. See [the install.md](https://github.com/FoxUSA/OpenNote/blob/master/docs/Install.md) for some examples

> Is it possible for a user to configure the app to save directly to services like dropbox?
No. Mostly because I have tried to keep in the oss ecosystem. I have seen that dropbox integrations are popular. It is not something I would use so it hasn't made its way into the project.

> edit: After installing the latest OpenNote version on my website it looks like the editor CKEditor does not ship with OpenNote. Are there instructions for getting this to work?
Don't know about this one. Have seen this a couple of times. In the most recent release I have pulled out CKEditor in favor of markdown(like github). I do need to update the screenshots.

**Comment by slipgatekid** [comment]
Other issues aside, the fact that you are moving Opennote to markdown is a huge disappointment to me. As someone who sees WYSIWYG formatting as an integral part of note taking, Markdown is useless to me. Opennote is/was the remaining cross-platform note taking app that uses a richtext editor. I wish software designers and programmers could see beyond their narrow focus on this issue.
